package mx.uaemex.fi.ico.linc26.estacionamiento.admin.controller;

public enum ControllerDirectory {
	ADMIN_LOGIN,
	ADMIN_CENTER,
	FINGERPRINT_IO,
	USER_MANGMENT,
	ADD_NEW_USER,
	SHOW_OR_EDIT_EXISTING_USER,
	DELETE_EXISTING_USER,
	SHOW_ALL_USERS,
	VEHICLE_MANAGMENT,
	ADD_NEW_VEHICLE,
	SHOW_OR_EDIT_EXISTING_VEHICLE,
	DELETE_EXISITING_OWNER_VEHICLE,
	DELETE_EXISTING_VEHICLE,
	SHOW_ALL_VEHICLES,
	FIND_VEHICLE_OWNER,
	PAY_PERIODIC_FEE,
	EXPLORE_LOGS,
	HSAMPLE
}
